#Codes and static resources are mounted. No rebuild is needed
#for changes of codes and static resources.
version: "3.9"

services:
  account-api:
    build: .
    image: account-api
    container_name: account-api
    restart: on-failure
    # Migrate only once when using MongoDB and Djongo
    # command: ["sh", "-c", "python manage.py makemigrations --no-input && python manage.py migrate --no-input && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"]
    # command: ["sh", "-c", "tail -f /dev/null"]
    # command: ["sh", "./wait-for", "mongo:27017", "--", "sh", "-c", "tail -f /dev/null"]
    # command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]
    command: [ "sh", "-c", "while sleep 1000; do :; done" ]
    env_file:
      - ./.env.dev
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - default
      - commanddb
      - esdb
      - querydb
      - redis
      - rabbit
  account-worker:
    image: account-api
    container_name: account-worker
    restart: on-failure
    command:
      [
        "sh",
        "./wait-for",
        "account-api:8000",
        "--",
        "sh",
        "-c",
        "celery -A account worker --concurrency=2 -l INFO -O fair"
      ]
    env_file:
      - ./.env.dev
    volumes:
      - .:/home/app
    depends_on:
      - account-api
    networks:
      - default
      - redis
      - rabbit

networks:
  default:
    name: account-api
  commanddb:
    name: postgres
    external: true
  esdb:
    name: esdb
    external: true
  querydb:
    name: mongo
    external: true
  redis:
    name: redis
    external: true
  rabbit:
    name: rabbit
    external: true
